#!/bin/bash

set -ex

scriptpath="$(readlink -f "$0")"
SLIM_CFG_TOP_DIR="${scriptpath%/${0##*/}}"
SLIM_CFG_OPENWRT_BRANCH="openwrt-21.02"
# base on branch 21.02 2021.02.26
SLIM_CFG_OPENWRT_COMMIT="2ce89a35788fcd768a4a872d3d4f5a3a131b1d43"
SLIM_CFG_OPENWRT_ABBREV_COMMIT=$( echo "$SLIM_CFG_OPENWRT_COMMIT" | cut -b 1-7 )
SLIM_CFG_OPENWRT_VERSION="21.02"
SLIM_CFG_TARGET="x86"
SLIM_CFG_ARCH="64"

SLIM_CFG_DOWNLOAD_PATH="$SLIM_CFG_TOP_DIR/downloaded"
SLIM_CFG_CLONE_PATH="$SLIM_CFG_TOP_DIR/downloaded/$SLIM_CFG_OPENWRT_BRANCH-$SLIM_CFG_OPENWRT_ABBREV_COMMIT"

if [ -z $SLIM_CFG_PROFILE ]
then
    SLIM_CFG_PROFILE="slim"
fi

echo Work with profile : $SLIM_CFG_PROFILE
SLIM_CFG_PROFILE_DIR="$SLIM_CFG_TOP_DIR/profiles/$SLIM_CFG_PROFILE"


# should override by profile
SLIM_CFG_WORK_PATH=""
SLIM_CFG_BIN_IMG_DIR=""
SLIM_CFG_PATCHES_MODULES=""
